import type { Config } from "@/config/schema";
import { readLockFile, rebuildLockFile } from "@/core/diff-checker";
import { generateComponent } from "@/core/component-generator";
import { optimizeSVG } from "@/core/svg-processor";
import { logger } from "@/utils/logger";
import { execSync } from "child_process";
import fs from "fs/promises";
import { existsSync } from "fs";
import path from "path";

export interface HookOptions {
  projectRoot: string;
  config?: Config;
  subcommand: "install" | "uninstall" | "status" | "run";
  husky?: boolean;
  warn?: boolean;
  fix?: boolean;
}

const HOOK_SIGNATURE = "# mkicon pre-commit hook";

const getGitHooksDir = (projectRoot: string): string =>
  path.join(projectRoot, ".git", "hooks");

const getPreCommitPath = (projectRoot: string, husky: boolean): string =>
  husky
    ? path.join(projectRoot, ".husky", "pre-commit")
    : path.join(getGitHooksDir(projectRoot), "pre-commit");

const buildHookScript = (warn: boolean): string => {
  const mode = warn ? "--warn" : "--enforce";
  return `#!/bin/sh
${HOOK_SIGNATURE}
# Auto-generated by: mkicon hook install
# Remove with: mkicon hook uninstall
mkicon hook run ${mode}
`;
};

const install = async (projectRoot: string, husky: boolean, warn: boolean): Promise<void> => {
  const hookPath = getPreCommitPath(projectRoot, husky);
  const hookDir = path.dirname(hookPath);

  if (!existsSync(hookDir)) {
    if (husky) {
      await fs.mkdir(hookDir, { recursive: true });
    } else {
      logger.error(`Git hooks directory not found: ${hookDir}`);
      logger.print("Make sure you are in a git repository.");
      process.exit(1);
    }
  }

  // If hook exists and isn't ours, preserve it
  if (existsSync(hookPath)) {
    const existing = await fs.readFile(hookPath, "utf-8");
    if (!existing.includes(HOOK_SIGNATURE)) {
      logger.error("A pre-commit hook already exists and was not created by mkicon.");
      logger.print("To integrate manually, add the following line to your hook:");
      logger.print("  mkicon hook run");
      process.exit(1);
    }
    // Already installed — overwrite (update)
  }

  const script = buildHookScript(warn);
  await fs.writeFile(hookPath, script, { encoding: "utf-8", mode: 0o755 });

  const mode = warn ? "warn" : "enforce";
  logger.success(`Pre-commit hook installed (${mode} mode): ${path.relative(projectRoot, hookPath)}`);

  if (husky) {
    logger.info("Make sure you have run 'npx husky init' and that husky is configured.");
  }
};

const uninstall = async (projectRoot: string, husky: boolean): Promise<void> => {
  const hookPath = getPreCommitPath(projectRoot, husky);

  if (!existsSync(hookPath)) {
    logger.info("No pre-commit hook found.");
    return;
  }

  const content = await fs.readFile(hookPath, "utf-8");

  if (!content.includes(HOOK_SIGNATURE)) {
    logger.error("The pre-commit hook was not created by mkicon — skipping.");
    process.exit(1);
  }

  await fs.unlink(hookPath);
  logger.success(`Pre-commit hook removed: ${path.relative(projectRoot, hookPath)}`);
};

const status = async (projectRoot: string): Promise<void> => {
  const regular = path.join(getGitHooksDir(projectRoot), "pre-commit");
  const huskyPath = path.join(projectRoot, ".husky", "pre-commit");

  const check = async (p: string, label: string): Promise<void> => {
    if (!existsSync(p)) {
      logger.print(`  ${label}: not found`);
      return;
    }
    const content = await fs.readFile(p, "utf-8");
    if (content.includes(HOOK_SIGNATURE)) {
      const isWarn = content.includes("--warn");
      logger.print(`  ${label}: installed (${isWarn ? "warn" : "enforce"} mode)`);
    } else {
      logger.print(`  ${label}: exists (not managed by mkicon)`);
    }
  };

  logger.separator();
  await check(regular, ".git/hooks/pre-commit");
  await check(huskyPath, ".husky/pre-commit      ");
  logger.separator();
};

const getStagedIconFiles = (projectRoot: string, config: Config): string[] => {
  try {
    const output = execSync("git diff --cached --name-only", {
      cwd: projectRoot,
      encoding: "utf-8",
    });
    const staged = output.trim().split("\n").filter(Boolean);
    const iconsRelDir = path.join(config.baseDir, config.iconsFolder).replace(/\\/g, "/");
    return staged.filter((f) => f.replace(/\\/g, "/").startsWith(iconsRelDir));
  } catch {
    return [];
  }
};

const getStagedContent = (projectRoot: string, relPath: string): string | null => {
  try {
    return execSync(`git show ":${relPath.replace(/\\/g, "/")}"`, {
      cwd: projectRoot,
      encoding: "utf-8",
    });
  } catch {
    return null;
  }
};

export const runHook = async (options: HookOptions): Promise<void> => {
  const { projectRoot, config, subcommand, husky = false, warn = false, fix = false } = options;

  if (subcommand === "install") {
    await install(projectRoot, husky, warn);
    return;
  }

  if (subcommand === "uninstall") {
    await uninstall(projectRoot, husky);
    return;
  }

  if (subcommand === "status") {
    await status(projectRoot);
    return;
  }

  // subcommand === "run" — the actual pre-commit check
  if (!config) {
    // No config → nothing to check, allow commit
    process.exit(0);
  }

  let lock = await readLockFile(projectRoot);

  if (Object.keys(lock).length === 0) {
    // Try rebuild before giving up
    const iconsDir = path.join(projectRoot, config.baseDir, config.iconsFolder);
    if (existsSync(iconsDir)) {
      await rebuildLockFile(projectRoot, iconsDir);
      lock = await readLockFile(projectRoot);
    }
    if (Object.keys(lock).length === 0) {process.exit(0);}
  }

  const stagedIconFiles = getStagedIconFiles(projectRoot, config);
  if (stagedIconFiles.length === 0) {process.exit(0);}

  const drifted: string[] = [];

  for (const relPath of stagedIconFiles) {
    const filename = path.basename(relPath);
    const entry = lock[filename];
    if (!entry) {continue;}

    const stagedContent = getStagedContent(projectRoot, relPath);
    if (stagedContent === null) {continue;}

    const processed = await optimizeSVG(entry.svgContent, config.optimize);
    const generated = await generateComponent({
      componentName: entry.componentName,
      svgContent: processed.content,
      viewBox: processed.viewBox,
      config,
    });

    if (stagedContent.trimEnd() !== generated.content.trimEnd()) {
      drifted.push(filename);
    }
  }

  if (drifted.length === 0) {process.exit(0);}

  process.stderr.write(`\nmkicon: ${drifted.length} icon component(s) have been manually edited:\n`);
  for (const f of drifted) {
    process.stderr.write(`  • ${f}\n`);
  }
  process.stderr.write("\n  Run 'mkicon diff' to see changes\n");

  if (fix) {
    process.stderr.write("  Auto-fixing and staging changes...\n");
    const iconsDir = path.join(projectRoot, config.baseDir, config.iconsFolder);

    for (const filename of drifted) {
      const entry = lock[filename];
      if (!entry) {continue;}

      const processed = await optimizeSVG(entry.svgContent, config.optimize);
      const generated = await generateComponent({
        componentName: entry.componentName,
        svgContent: processed.content,
        viewBox: processed.viewBox,
        config,
      });

      const outPath = path.join(iconsDir, filename);
      await fs.writeFile(outPath, generated.content, "utf-8");

      try {
        execSync(`git add "${outPath}"`, { cwd: projectRoot });
        process.stderr.write(`  Fixed and staged: ${filename}\n`);
      } catch {
        process.stderr.write(`  Fixed but failed to stage: ${filename}\n`);
      }
    }
    process.exit(0);
  }

  const enforce = !warn;
  if (enforce) {
    process.stderr.write("  Commit blocked. Use 'git commit --no-verify' to bypass.\n\n");
    process.exit(1);
  } else {
    process.stderr.write("  Warning only — commit allowed.\n\n");
    process.exit(0);
  }
};
