import type { Config } from "@/config/schema";
import { readLockFile, rebuildLockFile } from "@/core/diff-checker";
import { optimizeSVG } from "@/core/svg-processor";
import { logger } from "@/utils/logger";
import { toKebabCase } from "@/utils/naming";
import { existsSync } from "fs";
import fs from "fs/promises";
import path from "path";

export interface SpriteOptions {
  projectRoot: string;
  config: Config;
  output?: string;
  prefix?: string;
  optimize?: boolean;
  types?: boolean;
}

/**
 * Extract the viewBox attribute from an SVG string.
 */
const extractViewBox = (svg: string): string =>
  svg.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 24 24";

/**
 * Strip the outer <svg ...> wrapper and return only the inner elements.
 */
const extractInner = (svg: string): string => {
  const openEnd = svg.indexOf(">");
  const closeStart = svg.lastIndexOf("</svg>");
  if (openEnd === -1 || closeStart === -1) {return svg;}
  return svg.slice(openEnd + 1, closeStart).trim();
};

/**
 * Convert a component name to a symbol ID.
 * "ArrowUpIcon" → "arrow-up"  (strips trailing "Icon")
 * With prefix "icon-" → "icon-arrow-up"
 */
const toSymbolId = (componentName: string, prefix: string, config: Config): string => {
  const suffix = config.naming.suffix;
  const withoutSuffix =
    config.naming.suffixEnabled && componentName.endsWith(suffix)
      ? componentName.slice(0, -suffix.length)
      : componentName;

  return prefix + toKebabCase(withoutSuffix);
};

export const runSprite = async (options: SpriteOptions): Promise<void> => {
  const {
    projectRoot,
    config,
    output,
    prefix = "",
    optimize = true,
    types = false,
  } = options;

  // Load lock file — rebuild if missing
  let lock = await readLockFile(projectRoot);
  if (Object.keys(lock).length === 0) {
    const iconsDir = path.join(projectRoot, config.baseDir, config.iconsFolder);
    if (existsSync(iconsDir)) {
      logger.info("No lock file found — rebuilding from existing components...");
      await rebuildLockFile(projectRoot, iconsDir);
      lock = await readLockFile(projectRoot);
    }
  }

  const entries = Object.values(lock);
  if (entries.length === 0) {
    logger.warning("No tracked icons found. Generate some icons first.");
    process.exit(1);
  }

  logger.info(`Building sprite from ${entries.length} icon(s)...`);

  const symbols: string[] = [];
  const ids: string[] = [];

  for (const entry of entries) {
    let svgContent = entry.svgContent;

    if (optimize) {
      const processed = await optimizeSVG(svgContent, true);
      svgContent = processed.content;
    }

    const viewBox = extractViewBox(svgContent);
    const inner = extractInner(svgContent);
    const id = toSymbolId(entry.componentName, prefix, config);

    ids.push(id);
    symbols.push(
      `  <symbol id="${id}" viewBox="${viewBox}">\n    ${inner}\n  </symbol>`,
    );
  }

  // Build sprite
  const sprite = [
    `<!-- Generated by mkicon — ${new Date().toISOString()} -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`,
    ...symbols,
    `</svg>`,
  ].join("\n");

  // Resolve output path
  const outPath = output
    ? path.isAbsolute(output)
      ? output
      : path.resolve(process.cwd(), output)
    : path.join(projectRoot, config.baseDir, "icons.svg");

  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, sprite, "utf-8");
  logger.success(`Sprite written: ${path.relative(projectRoot, outPath)} (${entries.length} symbols)`);

  // TypeScript types
  if (types) {
    const typesPath = outPath.replace(/\.svg$/, ".d.ts");
    const typeContent = [
      `// Generated by mkicon`,
      `export type IconId =`,
      `${ids.map((id) => `  | '${id}'`).join("\n")  };`,
      ``,
      `export declare const icons: IconId[];`,
    ].join("\n");

    await fs.writeFile(typesPath, typeContent, "utf-8");
    logger.success(`Types written:  ${path.relative(projectRoot, typesPath)}`);
  }

  logger.newline();
  logger.print("Usage in HTML:");
  logger.print(`  <svg><use href="${path.relative(process.cwd(), outPath)}#${ids[0] ?? "icon-name"}"></use></svg>`);
  if (prefix) {
    logger.print(`\n  Symbol IDs use prefix "${prefix}": ${ids.slice(0, 3).join(", ")}…`);
  }
};
