import fs from 'fs/promises';
import path from 'path';
import { getFilesWithExtension } from '@/utils/paths.js';

/**
 * Update the index file with all icon exports
 */
export const updateIndexFile = async (
  iconsDir: string,
  extension: string
): Promise<void> => {
  const files = await getFilesWithExtension(iconsDir, extension);
  
  // Filter out index file itself
  const iconFiles = files
    .filter((file) => file !== 'index.ts' && file !== 'index.js')
    .sort();
  
  // Generate exports
  const exports = iconFiles.map((file) => {
    const componentName = file.replace(extension, '');
    const importPath = `./${componentName}`;
    return `export { ${componentName} } from '${importPath}';`;
  });
  
  const indexContent = `// Auto-generated by mkicon
// Do not edit manually - this file is updated automatically

${exports.join('\n')}
`;
  
  const indexPath = path.join(iconsDir, 'index.ts');
  await fs.writeFile(indexPath, indexContent, 'utf-8');
};
